general.import = ["~/.config/alacritty-theme/themes/rose_pine.toml"]
general.working_directory = 'C:\dev'

[env]
startup_mode = "Maximized"

[font]
size = 20.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[terminal.shell]
program = "bash"
